version: '3'

services:
  database:
    image: 'mongo'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    expose: 
      - 27017
    ports: 
      - 27017:27017

  backend:
    build: 'server/'
    expose:
      - '8889'
    ports:
      - '8889:8889'
    links:
      - 'database'
    working_dir: /server
    command: python3 server.py

  frontend:
    build: 'html/'
    expose:
      - '80'
      - '443'
    ports:
      - '80:80'
      - '443:443'
    links:
      - backend
